### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by denis-sokolov** [mwilliamson/node-options#1]
I would like to see a few new features added to the library as well as see new version numbers such as `1.0.0` released. Would you be open to PRs and new releases?
Or would you rather see the efforts go into something more active, like [data.maybe](https://www.npmjs.com/package/data.maybe)? In that case I'd recommend adding a note on the project page recommending the more maintained alternative.
Thanks for letting me know!

**Comment by mwilliamson** [comment]
I'd certainly be open to pull requests if they fitted with the project, I just haven't needed to add anything for a while. Out of curiosity, is there a reason you'd prefer this project to the alternatives?

**Comment by denis-sokolov** [comment]
I only found one reasonable alternative, the `data.maybe` package. No strong reason to choose one over the other.
Option/Some is slightly more popular naming pattern as opposed to Maybe/Just.
The source code of `node-options` is very short and simple while the other package has a bit of extra stuff. Not much, but still.
Finally, the `data.maybe` is partially a part of [Folktale](http://folktalejs.org/), and as a result it contains a few things specific to that collection, while the goal of `node-options` is clearly to be very standalone.

I was using this for a while and mainly missed the `.get`, `.isSome`/`.isNone` and `fromNullable` features.
I shall make PRs for these. As for the version, moving to proper semver and `1.0.0` allows easier upgrades for dependants.

**Comment by denis-sokolov** [comment]
PRs submitted, this issue is covered.
